apiVersion: v1
kind: Service
metadata:
  name: vault-dev-metallb
  namespace: __NAMESPACE__
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault-dev
    app.kubernetes.io/component: loadbalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: __METALLB_IP__
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault-dev
    component: server
  ports:
    - name: https-api
      port: 8200
      protocol: TCP
      targetPort: 8200
    - name: https-cluster
      port: 8201
      protocol: TCP
      targetPort: 8201
